### ISSUE TITLE
About the max-length of encoding

### ISSUE THREAD

**Issue by TRUMANCFY** [orionw/FollowIR#4]
Hi,

Thank you for the great work. I notice that the length of the corpus in the dataset is usually very long, e.g., 2297.97 words on average in the corpus of robust04-instructions.

However, I did not notice the configure of the max length within the code. I would like to double check whether it has been considered within the experimental setups.

Thank you in advance.

**Comment by orionw** [comment]
Hi @TRUMANCFY and thanks for the interest!

That's interesting, I saw different results for the word length:
```
from datasets import load_dataset
import numpy as np

dataset = "jhu-clsp/robust04-instructions"
dataset = load_dataset(dataset, "corpus")["corpus"]

word_len = []
for item in dataset:
    word_len.append(len((item["text"] + " " + item["title"]).split(" ")))

# print the percentiles every 5 from 0 to 100
percentiles = np.percentile(word_len, range(0, 101, 5))
print(percentiles)
```

Prints `[  9. 130. 198. 271. 341. 401. 401. 401. 401. 405. 406. 407. 407. 409.
 410. 412. 416. 421. 425. 430. 895.]`
 
 Do you mind sharing how you counted the words? Perhaps my quick count is wrong. The full robust04 docs **are** very long but these should be just snippets of them.
 
 --------
 
However, the model is based on [Mistral Instruct v0.2](https://huggingface.co/mistralai/Mistral-7B-Instruct-v0.2) which has a 32k context limit.  Like any LM, it probably won't do amazing at the limits (around 30k), but it should be able to take in decently long inputs if you need it to and should definitely be able to handle these datasets.

**Comment by TRUMANCFY** [comment]
Hi,

Thank you for the prompt reply! The way I count the word number is the same as yours. I agree with you that it won't greatly affect the performance of LLM-based retrievers, as they mostly have a large context window. However, the non-instruction baselines, e.g., contriever, may be different, or probably better if setting the max_length to the maximum possible, e.g., 512 for bert-based models.

I would just kindly remind you whether this is a fair comparison against the baselines which are limited to the window size.

Can we have better way to conduct the comparison?

**Comment by orionw** [comment]
> I would just kindly remind you whether this is a fair comparison against the baselines which are limited to the window size.

From Table 1 in the [paper](https://arxiv.org/pdf/2403.15246) you can see that most queries are 10 words and most instructions are less than 70 words.  ~~Thus, most sets are around 480 ish words (which I agree is more than 512 tokens but not by much - probably only missing the last sentence or two).~~

EDIT: **ah just remembered that they embed separately (bi-encoders). Nearly all of the data instances will fit in the context length. I think this is a non-issue as 99%+ fit inside 512 tokens (see percentiles above).**

~~As you mention, this only affects the old BERT models like Contriever and E5.About half of the non-instruction baselines can take it though (MonoT5, BM25, etc) and they show the same trend as Contriever.~~  FWIW, I added [RepLlama](https://huggingface.co/castorini/repllama-v1-7b-lora-passage) recently and although I haven't updated the paper, it also shows the same trend and is also really bad at instructions. 

Part of the problem is that most modern retrievers use some form of instructions. Contriever is a really weak baseline these days (rank 123 in [MTEB](https://huggingface.co/spaces/mteb/leaderboard)) but I suppose one of the last ones that didn't use instructions. 

> Can we have better way to conduct the comparison?

If you think this 1% is especially concerning, you're welcome to try a [Max-P approach](https://arxiv.org/abs/1905.09217) to aggregating over longer passages.  I don't expect much if anything would change but if you do end up running it, I'd love to hear the results!

**Comment by TRUMANCFY** [comment]
Great! I really appreciate the work and again thank you for the reply! Issue closed.

**Comment by orionw** [comment]
Of course! Let me know if you have any other questions and good luck :)
